### ISSUE TITLE
yamato - Calling `exitLateById` twice will lead to permanent lock of user funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#19]
yamato

medium

# Calling `exitLateById` twice will lead to permanent lock of user funds

## Summary
Users will be locked out of their funds forever

## Vulnerability Detail
Calling `exitLateById` twice, will deduct the locked amount twice. This is problematic, as users would have incentive to call it in certain scenarios such as: 

1. User had locked for 360 days. `defaultRelockTime == 30 days`
2. 370 days have passed. User calls `exitLateById`. His unlock timestamp is set to 390 days.
3. Owner of the contract changes `defaultRelockTime` to 15 days.
4. If user now calls again `exitLateById`, their unlock timestamp will be changed to 375 days, hence they're incentivized to do it and they do it.
5. Now, if the user has had enough outstanding balance from other locks, the protocol would double-spend this lock's amount.
6. Now since the user's balance is lower than what it is supposed to be, last to be unlocked locks will revert due to underflow of user's balance.

## Impact
DoS, loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L349

## Tool used

Manual Review

## Recommendation
Either do not allow calling `exitLateById` twice on the same lock, or do not deduct user's amount for the 2nd time

Duplicate of #45

**Comment by yamato1x** [comment]
@santipu03 After going through all submissions, only mine and #204 showcase a realistic scenario where the user is incentivized to call this function twice and it would not be due to a mistake. I believe both of them should be valid.

Since I do not yet meet the escalation threshold please escalate on my behalf @santipu03 @pkqs90

**Comment by santipu03** [comment]
As I commented in #204, the value of `defaultRelockTime` won't be updated, so this issue won't be triggered.

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
