### ISSUE TITLE
pkqs90 - User can call `exitLateById()` multiple times for the same lockId to shorten his unlock period

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#204]
pkqs90

medium

# User can call `exitLateById()` multiple times for the same lockId to shorten his unlock period

## Summary

The function `exitLateById()` is used for users to execute a late exit for a lockId, and the unlock time will be precalculated. However, users can call `exitLateById()` again if the `defaultRelockTime` changes to his benefit, potentially resulting in a shorter unlock period.

## Vulnerability Detail

The core issue is `exitLateById()` function does not check whether the lock has already been exitedLate-ed or not. The user can call this function for a lock that has already been exitedLate-ed, and the unlock time will be recalculated. Since the unlock time is dependent on a changeable `defaultRelockTime` variable, the user may toy with this function to achieve a shorter unlock period, which is unexpected.

An example of user shortening his unlock period is:

1. User stakes for 300 days, and the `defaultRelockTime` is 60 days.
2. 310 days has passed. User calls `exitLateById()` for this lock. The remaining unlock period is 50 days.
3. Admin changes `defaultRelockTime` to 30 days.
4. User calls `exitLateById()` again, and the unlock period will be recalculated and shortened to 20 days.

Note that the `defaultRelockTime` does not have to always decrease in order for users to achieve a shorter unlock period. For example, user originally stakes for 300 days, and `defaultRelockTime` is 50. At day 355, the remaining unlock period would be 45 days, but if `defaultRelockTime` is changed to 60, the remaining unlock period would be only 5 days.

Also note that though the user's `lockedWithMultiplier` would double-decrease due to calling `exitLateById()` multiple times. The core issue here is that users can toy with the `exitLateById()` mechanism to achieve a shorter unlock period, which should be unexpected.

```solidity
    function exitLateById(uint256 id) external {
        _updateReward(msg.sender); // Updates any pending rewards for the caller before proceeding.

        LockedBalance memory lockedBalance = locklist.getLockById(msg.sender, id); // Retrieves the lock details from the lock list as a storage reference to modify.

        // Calculate and set the new unlock time based on the remaining cooldown period.
>       uint256 coolDownSecs = calcRemainUnlockPeriod(lockedBalance);
        locklist.updateUnlockTime(msg.sender, id, block.timestamp + coolDownSecs);

        // Reduce the locked supply and the user's locked balance with and without multiplier.
        uint256 multiplierBalance = lockedBalance.amount * lockedBalance.multiplier;
        lockedSupplyWithMultiplier -= multiplierBalance;
        lockedSupply -= lockedBalance.amount;
        Balances storage bal = balances[msg.sender];
        bal.lockedWithMultiplier -= multiplierBalance;
        bal.locked -= lockedBalance.amount;

        locklist.setExitedLateToTrue(msg.sender, id);

        _updateRewardDebt(msg.sender); // Recalculates reward debt after changing the locked balance.

        emit ExitLateById(id, msg.sender, lockedBalance.amount); // Emits an event logging the details of the late exit.
    }

    function calcRemainUnlockPeriod(LockedBalance memory userLock) public view returns (uint256) {
        uint256 lockTime = userLock.lockTime;
        uint256 lockPeriod = userLock.lockPeriod;
        
        if (lockPeriod <= defaultRelockTime || (block.timestamp - lockTime) < lockPeriod) {
            // If the adjusted lock period is less than or equal to the default relock time, or if the current time is still within the adjusted lock period, return the remaining time based on the adjusted lock period.
            return lockPeriod - (block.timestamp - lockTime) % lockPeriod;
        } else {
            // If the current time exceeds the adjusted lock period, return the remaining time based on the default relock time.
            return defaultRelockTime - (block.timestamp - lockTime) % defaultRelockTime;
        }
    }
```

## Impact

Users can toy with the `exitLateById()` mechanism to achieve a shorter unlock period.

## Code Snippet

- https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L349-L371

## Tool used

Manual review

## Recommendation

Add a check that the lock entering `exitLateById()` does not have `.exitedLate == true`.

Duplicate of #45

**Comment by pkqs90** [comment]
Escalate

This is not a duplicate to #45. #45 only mentions that a user can call `exitLateById()` multiple times for the same lockId he owns, but does not describe how the user can benefit from it.

This issue highlights a scenario where a user can shorten the lock period that he was suppose to be locked for, which is unexpected. Indeed, the user will lose some of the staked tokens (due to double subtraction), but the main issue is there is an attack path to successfully shorten the locking period, which is a valid issue.

**Comment by santipu03** [comment]
This issue was marked as a dup of #45 because the root cause is the same, which is that a user can exit late lock twice, losing funds. 

Moreover, the sponsor clarified in the Discord channel that the `defaultRelockTime` would always be 30 days, and your report assumes that the value of `defaultRelockTime` will be updated.

**Comment by pkqs90** [comment]
1. The code has a function and clear comments that the contract owner can update the default relock time.
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L108C1-L114C1

```solidity
    /// @notice Sets the minimum relock time after a late exit.
    /// @dev This function can only be called by the contract owner and updates the default relock time.
    /// @param _defaultRelockTime The new default relock time in seconds.
    function setDefaultRelockTime(uint256 _defaultRelockTime) external onlyOwner {
        defaultRelockTime = _defaultRelockTime;
    }
```

2. Sponsor only quoted the paragraph in https://github.com/sherlock-audit/2024-05-gamma-staking/tree/main/StakingV2, which said `In practice, the staking token will be our governance token that will only have one visible option on frontend for a 30-day lock with defaultLockPeriod also equal to 30 days. `. The point here is "in practice" it should be 30 days, but never said that `defaultRelockTime` cannot be updated.
![image](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/4862706/2eecdec8-97be-47c0-b8ea-647741dac499)

3. The main readme https://github.com/sherlock-audit/2024-05-gamma-staking also states in that `defaultRelockTime` can be updated: `The defaultRelockPeriod is also intended to be upgradeable by owner.`

**Comment by santipu03** [comment]
I asked the sponsor in the Discord channel:

![image](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/assets/90318659/83af01cc-4676-4544-9b20-c13bf496886f)

It may be confusing because there's an extra question in between my question and the answer but it was just bad timing. The "Yes correct" answer was given to my question because it's not a logic answer for the question in between, which is answered later.

**Comment by pkqs90** [comment]
Thanks, I didn't see that message.

But to be honest this message is very vague, and it also contradicts with the 1) code comments, 2) readme, and even the unit tests have a test for the `setDefaultRelockTime` function.

Also, the latest Sherlock rules [here](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards) states that 1) `contest README or CODE COMMENTS, that information stands above all judging rules` 2) `screenshots are not considered sources of truth while judging an issue/escalation especially if they are conflicting with the contest README.`.

**Comment by yamato1x** [comment]
`setDefaultRelockTime` exists, so it is expected that it will/ can be used.

Also, cannot meet the threshold to escalate, but #19 also describes why the issue can happen without a user mistake, so if the escalation gets accepted, #19 should be a dup

**Comment by santipu03** [comment]
I don't believe there's a contradiction between the sponsor's comment and the other sources of truth:

1. The README states that `defaultRelockPeriod` is intended to be upgradeable, which doesn't mean that MUST be updated.
2. The fact that there's a function to update the `defaultRelockPeriod` also doesn't mean that MUST be updated.
3. The fact that there are tests updating `defaultRelockPeriod` also doesn't mean that it MUST be updated when deployed. 

Indeed, the README and code comments indicate that `defaultRelockPeriod` CAN be updated, but the sponsor has stated that the value won't be updated.

**Comment by nevillehuang** [comment]
I agree with lead judge here. This issue is only possible because for the same lock Id, the user can exit late twice. The validity of this issue will be revisited on the primary issue #45. Additionally, it is also dependent on a decrease in `defaultRelockTime` so seems invalid based on the following sherlock guideline.

> > 3. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Planning to reject escalation and leave issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #45

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [pkqs90](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/204/#issuecomment-2137390230): rejected
