### ISSUE TITLE
pkqs90 - Staking dust amount for other users can cause `withdrawAllUnlockedToken()` to DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#214]
pkqs90

medium

# Staking dust amount for other users can cause `withdrawAllUnlockedToken()` to DoS

## Summary

The protocol allows staking on behalf of another user, however, it does not limit the minimum amount of tokens. Attackers can perform a grief attack by staking dust amount (1 wei) for other users, and bloat up their locklist, which would brick the user calling `withdrawAllUnlockedToken()`.

## Vulnerability Detail

There are two issues here:

1. Attackers can stake dust amount (e.g. 1 wei) of stakingToken for a victim. This would bloat up their locklist.
2. Users calling `withdrawAllUnlockedToken()` must iterate through ALL existing locks at a O(n^2) complexity, which is a waste of gas, and may easily lead to out-of-gas issues.

Issue 1 is easy to understand. Let's dive into issue 2:

The reason `withdrawAllUnlockedToken()` is a O(n^2) complexity is because the code queries `locklist.getLocks(msg.sender, page, lockCount)` instead of `locklist.getLocks(msg.sender, page, 10)` every time, where `lockCount` is the array length. The `locklist.getLocks(msg.sender, page, lockCount)` will return an array length of `lockCount`, and each element would be iterated every time.

Also, even if `withdrawAllUnlockedToken()` use a correct O(n) implemetation, it still may run into out-of-gas error, as long as attacker sends enough dust amount locks into the locklist of the victim.

Lock.sol
```solidity
    function _stake(
        uint256 amount,
>       address onBehalfOf,
        uint256 typeIndex,
        bool isRelock
    ) internal whenNotPaused {
        if (typeIndex >= lockPeriod.length || amount == 0) revert InvalidAmount();

        _updateReward(onBehalfOf);
        
        Balances storage bal = balances[onBehalfOf];

        bal.locked += amount;
        lockedSupply += amount;

        uint256 multiplier = rewardMultipliers[typeIndex];
        bal.lockedWithMultiplier += amount * multiplier;
        lockedSupplyWithMultiplier += amount * multiplier;
        _updateRewardDebt(onBehalfOf);


>       locklist.addToList(
            onBehalfOf, 
            LockedBalance({
                lockId: 0, // This will be set inside the addToList function
                amount: amount,
                unlockTime: 0, 
                multiplier: multiplier,
                lockTime: block.timestamp,
                lockPeriod: lockPeriod[typeIndex],
                exitedLate: false
            })
        );

        if (!isRelock) {
            IERC20(stakingToken).safeTransferFrom(
                msg.sender,
                address(this),
                amount
            );
        }

        emit Locked(
            onBehalfOf,
            amount,
            balances[onBehalfOf].locked
        );
    }
    ...
    function withdrawAllUnlockedToken() external override nonReentrant {
        uint256 lockCount = locklist.lockCount(msg.sender); // Fetch the total number of locks for the caller.
        uint256 page;
        uint256 limit;
        uint256 totalUnlocked;
        
        while (limit < lockCount) {
>           LockedBalance[] memory lockedBals = locklist.getLocks(msg.sender, page, lockCount); // Retrieves a page of locks for the user.
            for (uint256 i = 0; i < lockedBals.length; i++) {
                if (lockedBals[i].unlockTime != 0 && lockedBals[i].unlockTime < block.timestamp) {
                    totalUnlocked += lockedBals[i].amount; // Adds up the amount from all unlocked balances.
                    locklist.removeFromList(msg.sender, lockedBals[i].lockId); // Removes the lock from the list.
                }
            }

>           limit += 10; // Moves to the next page of locks.
            page++;
        }

        IERC20(stakingToken).safeTransfer(msg.sender, totalUnlocked); // Transfers the total unlocked amount to the user.
        emit WithdrawAllUnlocked(msg.sender, totalUnlocked); // Emits an event logging the withdrawal.
    }
```

Locklist.sol
```solidity
    function getLocks(
        address user,
        uint256 page,
        uint256 limit
    ) public view override returns (LockedBalance[] memory) {
>       LockedBalance[] memory locks = new LockedBalance[](limit);
        uint256 lockIdsLength = lockIndexesByUser[user].length();

        uint256 i = page * limit;
        for (;i < (page + 1) * limit && i < lockIdsLength; i ++) {
            locks[i - page * limit]= lockById[lockIndexesByUser[user].at(i)];
        }
        return locks;
    }
```

## Impact

Users would not be able to call `withdrawAllUnlockedToken()` due to out-of-gas error.

## Code Snippet

- https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L260-L307
- https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/libraries/LockList.sol#L97-L110

## Tool used

Manual review

## Recommendation

1. Implement `withdrawAllUnlockedToken()` correctly: change to `locklist.getLocks(msg.sender, page, 10)` and add a `gasleft()` check.
2. Maybe maintain a list of trusted users for each address, and limit only these users can stake on behalf of them.

**Comment by rekxor** [comment]
But the function can be gamed and the user can be gas-griefed if he calls the function, causing him loss

**Comment by sa9933** [comment]
Escalate:

If anyone has escalation rights, please escalate this issue. @santipu03, @pkqs90, @nevillehuang, @rekxor, or anyone else.

I believe this issue should be classified as medium severity. As stated by @santipu, although users can still withdraw unlock tokens by ID one by one, the intended functionality of the contract was to allow users to withdraw all unlock tokens in one go. This function, which was intended to work properly by protocol, can be subjected to a Denial of Service (DoS) attack. According to the Sherlock documentation (https://docs.sherlock.xyz/audits/judging/judging#:~:text=Breaks%20core%20contract%20functionality%2C%20rendering%20the%20contract%20useless%20or%20leading%20to%20loss%20of%20funds), the core contract functionality regarding withdrawAllUnlockedToken() is not working as the protocol intended.

**Comment by sherlock-admin3** [comment]
> Escalate:
> 
> If anyone has escalation rights, please escalate this issue. @santipu03, @pkqs90, @nevillehuang, @rekxor, or anyone else.
> 
> I believe this issue should be classified as medium severity. As stated by @santipu, although users can still withdraw unlock tokens by ID one by one, the intended functionality of the contract was to allow users to withdraw all unlock tokens in one go. This function, which was intended to work properly by protocol, can be subjected to a Denial of Service (DoS) attack. According to the Sherlock documentation (https://docs.sherlock.xyz/audits/judging/judging#:~:text=Breaks%20core%20contract%20functionality%2C%20rendering%20the%20contract%20useless%20or%20leading%20to%20loss%20of%20funds), the core contract functionality regarding withdrawAllUnlockedToken() is not working as the protocol intended.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by santipu03** [comment]
@sa9933 A specific function is not considered a core contract functionality, but the withdrawal mechanism is. Even if `withdrawAllUnlockedToken` is DoSed, the withdrawal functionality is still working through `withdrawUnlockedTokenById`.

**Comment by rekxor** [comment]
The functionality of withdrawal of all tokens introduced for ease of user has a flaw, and that being overshadowed by a function in which a user who has staked much number of tokens need to spend more gas by calling the `withdrawUnlockedTokenById()` function as many number of times as his tokens staked. While the intended function aimed at doing so by a single Tx

**Comment by Karan9034** [comment]
> The functionality of withdrawal of all tokens introduced for ease of user has a flaw, and that being overshadowed by a function in which a user who has staked much number of tokens need to spend more gas by calling the `withdrawUnlockedTokenById()` function as many number of times as his tokens staked. While the intended function aimed at doing so by a single Tx

Adding to this, since any malicious user can stake on behalf of someone the length of `lockList` could grow unbounded. To know the `lockId` of user's real deposits, user has to check all the lock ids and withdraw each individually. This would be like finding a needle in a haystack. `withdrawAllUnlockedToken` function is specifically there to tackle this scenario, isn't it?

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
