### ISSUE TITLE
maushish - `recoverERC20` and `_getReward` current implementation allows some user's funds to be locked in the contract for forever.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#219]
maushish

medium

# `recoverERC20` and `_getReward` current implementation allows some user's funds to be locked in the contract for forever.

## Summary
The current implementation of `recoverERC20` & `_getReward` allows some user's funds to be locked in the contract forever
## Vulnerability Detail
>[!NOTE]
USDC/USDT can blacklist any user.

```solidity
    /// @notice Transfers accrued rewards for specified tokens to the user.
    /// @dev Iterates through the list of reward tokens and transfers each accrued reward to the user's address, provided the reward amount is greater than zero.
    ///      This function also updates the reward balances and logs the reward payments.
    /// @param _user The address of the user receiving the rewards.
    /// @param _rewardTokens An array of reward token addresses from which the user is claiming rewards.
    //audit: rewards arent claimable if the user is blocklisted of a particular token
    function _getReward(
        address _user,
        address[] memory _rewardTokens
    ) internal whenNotPaused {
        uint256 length = _rewardTokens.length; // Get the number of reward tokens to process.
        for (uint256 i = 0; i < length; ) {
            address token = _rewardTokens[i]; // Get the current token address.

            uint256 reward = rewards[_user][token]; // Retrieve the amount of reward due for the user and the token.
            if (reward > 0) {
                rewards[_user][token] = 0; // Reset the reward to zero after claiming.
                rewardData[token].balance -= reward / 1e36; // Deduct the reward from the stored balance, adjusting for decimals.

                IERC20(token).safeTransfer(_user, reward / 1e36); // Transfer the reward to the user.
                rewardPaid[_user][token] += reward / 1e36; // Update the total reward paid to the user for this token.
                emit RewardPaid(_user, token, reward / 1e36); // Emit an event documenting the reward payment.
            }
            unchecked {
                i++;
            }
        }
    }
```
As you see in `_getReward` if any user gets blacklisted by USDC/USDT, it would lead to transactions reverting.
The bigger issue is in the array of `RewardTokens`. Here is a scenario for better understanding.
Assume there are 4 reward tokens whitelisted by the `ADMIN` (X, Y, USDC, USDT). 
Now, depending on how the tokens are set in the array, the amount of reward will vary.
>**Case:** [usdc, x, y, usdt]
>In this case, the loop won't be going to even the second RewardToken(x) making him lose all of his rewards

>[!IMPORTANT]
Now normally in the above case `recoverERC20` should be helpful, but the current implementation only allows recovery of non-active RewardToken which in the above case wont be true coz user can able to claim them in the first place

```solidity

    /// @notice Allows the contract owner to recover ERC-20 tokens sent to the contract under specific conditions.
    /// @dev This function can only be executed by the contract owner and is meant for recovering tokens that are not actively being used as rewards or are not the staking token itself.
    ///      It checks if the token is currently active as a reward or if it's the staking token to prevent accidental or unauthorized recovery.
    /// @param tokenAddress The address of the ERC-20 token to be recovered.
    /// @param tokenAmount The amount of the token to be recovered.
    function recoverERC20(
        address tokenAddress,
        uint256 tokenAmount
    ) external onlyOwner {
        if (rewardData[tokenAddress].lastUpdateTime != 0) revert ActiveReward(); // Ensure the token is not currently active as a reward.
        if (tokenAddress == stakingToken) revert WrongRecoveryToken(); // Prevent recovery of the staking token.
        IERC20(tokenAddress).safeTransfer(owner(), tokenAmount); // Transfer the specified amount of the token to the contract owner.
        emit Recovered(tokenAddress, tokenAmount); // Emit an event to log the recovery operation.
    }
```

## Impact
Funds of users who are blacklisted cant be recovered from the contract ever.
## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L538
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L655
## Tool used

Manual Review

## Recommendation
- Create an implementation of 'recoverERC20` for blacklisting tokens.
- Implement a mechanism that allows users to claim token-specific rewards.
- As the no of users who gets blacklisted are pretty low there is no need for a permissionless mechanism for that instead `owner` can claim their rewards and forward it to them.

**Comment by maushish** [comment]
Hey @santipu03 i respectfully disagree with your reason.
I was well aware of the SherlockV2 document rule regarding blacklisted users, but my apologies for not showing the impact properly.
- **The impact will also be on protocol, as these [tokens's rewards can't be claimed by the user](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L538) and cannot be recovered by the administrator or owner of the contract using [recoverERC20](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L655) because they are *[active reward tokens.](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/703fd3604069489937037f20490ec8c492c0508e/StakingV2/src/Lock.sol#L652)***
- **Due to this, there will always be some rewards accumulated in the contract, which neither will pass to the blacklisted user nor can be transferred.**
>**For the above-stated reason, I believe my finding should be escalated.**

I am happy to answer any question, and if you think I am wrong, please provide a valid technical reason.

**Comment by BiasedMerc** [comment]
> Hey @santipu03 i respectfully disagree with your reason. I was well aware of the SherlockV2 document rule regarding blacklisted users, but my apologies for not showing the impact properly.
> 
>     * **The impact will also be on protocol, as these [tokens's rewards can't be claimed by the user](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L538) and cannot be recovered by the administrator or owner of the contract using [recoverERC20](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L655) because they are _[active reward tokens.](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/703fd3604069489937037f20490ec8c492c0508e/StakingV2/src/Lock.sol#L652)_**
> 
>     * **Due to this, there will always be some rewards accumulated in the contract, which neither will pass to the blacklisted user nor can be transferred.**
> 
> 
> > **For the above-stated reason, I believe my finding should be escalated.**
> 
> I am happy to answer any question, and if you think I am wrong, please provide a valid technical reason.

I do not think it's valid to say that this affects the protocol. These rewards have been earned by the blacklisted user, they do not technically belong to the protocol after being earned. The only harm is being done to the blacklisted user themselves.

See this similar issue [link](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/13#issuecomment-2120081987)

**Comment by santipu03** [comment]
I was just writing a similar response. Thanks @BiasedMerc.

**Comment by maushish** [comment]
@BiasedMerc Thanks for the response.
>I do not think it's valid to say that this affects the protocol. These rewards have been earned by the blacklisted user, they do not technically belong to the protocol after being earned. The only harm is being done to the blacklisted user themselves.

Here's why I disagree:
- Protocol's goal is to give stakers their rewards, and if the user is blocklisted by a certain token (USDC or USDT), it's a token-user issue, not a protocol-user issue.
>See this similar issue https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/13#issuecomment-2120081987

In this issue this part was already mentioned and I think the watson was right regarding judging rules not being implied properly, 
- Gamma's role was to give stakers their rewards, depending on how much the user stakes for a certain duration now due to some token blocklisting his/her address, and due to this, not allowing him to take the rest of the tokens is actually a mistake on the protocol side, not on the user side.

**Comment by maushish** [comment]
If you still think the issue should be invalid, I would suggest changing your Sherlock rules regarding blocklisted addresses and only accepting blocklisted address findings in the liquidation scenario.
Thanks for your time @santipu03 @BiasedMerc

**Comment by santipu03** [comment]
> Gamma's role was to give stakers their rewards, depending on how much the user stakes for a certain duration now due to some token blocklisting his/her address, and due to this, not allowing him to take the rest of the tokens is actually a mistake on the protocol side, not on the user side.

But still, in this scenario, the only harm is done to the user who cannot claim rewards. There's no harm done to the protocol so I still stand by my [first comment](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/219#issuecomment-2132928182).

**Comment by maushish** [comment]
>But still, in this scenario, the only harm is done to the user who cannot claim rewards. There's no harm done to the protocol so I still stand by my https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/219#issuecomment-2132928182.

Rewards getting locked in the contract is itself a harm, yeah I agree the user will be the one losing on rewards and I also believe no protocol wants unnecessary funds in their contract getting locked due to some user's mistake.
