### ISSUE TITLE
pkqs90 - `getAllRewards()` may revert on revert-on-zero-transfer ERC20 tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-05-gamma-staking-judging#229]
pkqs90

medium

# `getAllRewards()` may revert on revert-on-zero-transfer ERC20 tokens

## Summary

`getAllRewards()` iterates all reward tokens for the user, and may revert on revert-on-zero-transfer token if the transferred amount is zero.

## Vulnerability Detail

See the following code: the reward amount for each token is calculated as `reward / 1e36`, but the check only checks for `reward > 0`.

An example of revert-on-zero-transfer token is `LEND`.

Note that revert-on-zero-transfer tokens also fall under the "standard ERC-20 tokens", as stated in the contest readme.

```solidity
    /// @notice Retrieves and claims all pending staking rewards for the caller across all reward tokens.
    /// @dev This function serves as a convenience wrapper around the `getReward` function, applying it to all reward tokens currently recognized by the contract.
    function getAllRewards() external {
>       getReward(rewardTokens); // Calls the getReward function with the list of all reward tokens to claim all pending rewards.
    }

    function getReward(address[] memory _rewardTokens) public nonReentrant {
        _updateReward(msg.sender); // Updates any accrued rewards up to the current point for the caller.
        _getReward(msg.sender, _rewardTokens); // Calls the internal _getReward function to process the actual reward claim.
    }

    function _getReward(
        address _user,
        address[] memory _rewardTokens
    ) internal whenNotPaused {
        uint256 length = _rewardTokens.length; // Get the number of reward tokens to process.
        for (uint256 i = 0; i < length; ) {
            address token = _rewardTokens[i]; // Get the current token address.

            uint256 reward = rewards[_user][token]; // Retrieve the amount of reward due for the user and the token.
>           if (reward > 0) {
                rewards[_user][token] = 0; // Reset the reward to zero after claiming.
                rewardData[token].balance -= reward / 1e36; // Deduct the reward from the stored balance, adjusting for decimals.

>               IERC20(token).safeTransfer(_user, reward / 1e36); // Transfer the reward to the user.
                rewardPaid[_user][token] += reward / 1e36; // Update the total reward paid to the user for this token.
                emit RewardPaid(_user, token, reward / 1e36); // Emit an event documenting the reward payment.
            }
            unchecked {
                i++;
            }
        }
    }
```

## Impact

User may revert when calling `getAllRewards()` for revert-on-zero-transfer ERC20 tokens.

## Code Snippet

- https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L551

## Tool used

Manual review

## Recommendation

Change the check from `if (reward > 0)` to `if (reward / 1e36 > 0)`.

**Comment by pkqs90** [comment]
Escalate

Quoting the README:
> The tokens we expect to interact with would be standard ERC-20 tokens. The staking token will be a standard ERC-20 token. The reward tokens will also be standard ERC-20 tokens. There is a whitelisting process for which reward tokens we would allow to be used as rewardTokens in function addReward, which is an admin function. This process would only allow reward tokens that comply with the ERC-20 standard to be distributed to the stakers. We would also include USDC and USDT on the chains we mentioned in the previous question.

"Standard ERC-20 tokens" is vauge. It may mean ERC20 standard tokens, or "openzeppelin-like implementation" ERC20 tokens. If it the latter, then this is not a issue. If it is the former, then revert-on-zero tokens are also ERC-20 standard, which would make this issue valid.

Specifically this part of the readme made me thought that all ERC20 compatible tokens are included: `This process would only allow reward tokens that comply with the ERC-20 standard to be distributed to the stakers.`.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Quoting the README:
> > The tokens we expect to interact with would be standard ERC-20 tokens. The staking token will be a standard ERC-20 token. The reward tokens will also be standard ERC-20 tokens. There is a whitelisting process for which reward tokens we would allow to be used as rewardTokens in function addReward, which is an admin function. This process would only allow reward tokens that comply with the ERC-20 standard to be distributed to the stakers. We would also include USDC and USDT on the chains we mentioned in the previous question.
> 
> "Standard ERC-20 tokens" is vauge. It may mean ERC20 standard tokens, or "openzeppelin-like implementation" ERC20 tokens. If it the latter, then this is not a issue. If it is the former, then revert-on-zero tokens are also ERC-20 standard, which would make this issue valid.
> 
> Specifically this part of the readme made me thought that all ERC20 compatible tokens are included: `This process would only allow reward tokens that comply with the ERC-20 standard to be distributed to the stakers.`.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
I agree that the README wasn't that clear in specifying what it meant by "standard ERC-20 tokens".

I marked all weird ERC-20 tokens as invalid because, in my last contest as a lead judge, Evert told me that "standard ERC-20 tokens" meant that only the default ERC-20 implementation was in scope.

**Comment by pkqs90** [comment]
Okay, gonna leave that to the head of judge.

It should be noted that the README states `This process would only allow reward tokens that comply with the ERC-20 standard to be distributed to the stakers`, so the "standard ERC-20 tokens" it referred to previously should be equivalent to token that `comply with the ERC-20 standard`.

I think if these kind of confusion should be avoided either by Sherlock rules or making it clear in the readme (e.g. making the protocol team complete a checklist for erc20 token behaviors).

**Comment by santipu03** [comment]
Still, even if we consider "standard ERC-20 tokens" as tokens that just comply with the ERC-20 standard, I believe this issue doesn't actually warrant medium severity.

This bug will cause `_getReward` to revert in some specific scenarios, potentially causing a DoS on `getAllRewards`. However, a user can still call `getReward` to individually claim each reward token. This DoS doesn't block any functionality on the protocol.

**Comment by amankakar** [comment]
"standard ERC-20 tokens"  Does not include `revert-on-zero-transfer`.

**Comment by nevillehuang** [comment]
Based on sherlock rules, weird ERC20 tokens are only accepted unless explicitly mentioned:

> Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as weird-tokens are not considered valid by default unless these tokens are explicitly mentioned in the README.

Additionally, agree with @santipu03 comments that users can always get reward for individual tokens. Planning to reject escalation and leave issue as it is

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [pkqs90](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/229/#issuecomment-2137522692): rejected
