### ISSUE TITLE
NoOne - Precision Handling in the `_earned` Function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#24]
NoOne

high

# Precision Handling in the `_earned` Function

## Summary
The _earned function is designed to calculate the rewards accumulated by a user for a specific ERC-20 reward token. The function multiplies the cumulative reward per token with the user's locked balance (adjusted by a multiplier) and subtracts any previously accounted rewards (reward debt). An incorrect handling of precision by using 1e36 instead of 1e18 was identified, which could lead to significant miscalculations
## Vulnerability Detail
The key issue lies in the precision handling during the multiplication of two values, each with 18 decimal places. ERC-20 tokens typically use 18 decimal places for their values. When two such values are multiplied, the resulting value has 36 decimal places. To bring this value back to the standard 18 decimal places, it must be divided by 1e18. The original implementation failed to adjust for this, potentially leading to incorrect reward calculations.
## Impact
Without the division by 1e18, the reward calculations will result in significantly inflated values. This could lead to users receiving incorrect reward amounts.
## Code Snippet
[function _earned](https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L455)
## Tool used

Manual Review

## Recommendation
Always divide by 1e18 when multiplying two values that each have 18 decimal places. This ensures that the resulting value is scaled back to the standard 18 decimal places.

```solidity
function _earned(
        address _user,
        address _rewardToken
    ) internal view returns (uint256 earnings) {
        Reward memory rewardInfo = rewardData[_rewardToken]; // Retrieves reward data for the specified token.
        Balances memory balance = balances[_user]; // Retrieves balance information for the user.
        earnings =
            (rewardInfo.cumulatedReward *
            balance.lockedWithMultiplier) / 1e18  - //Delete by 1e18
            rewardDebt[_user][_rewardToken]; // Calculates earnings by considering the accumulated reward and the reward debt.
    }

```

**Comment by Jelev123** [comment]
i mean  balance.lockedWithMultiplier) / 1e18  - //Devision by 1e18
