### ISSUE TITLE
samuraii77 - Removing a reward token is not possible

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#287]
samuraii77

medium

# Removing a reward token is not possible

## Summary
Removing a reward token is not possible
## Vulnerability Detail
According to the contest README, it is possible to remove a reward. However, this functionality is not actually implemented and it is not possible for a reward to be removed from the `rewardTokens` array. This could cause issues as first of all, it is unexpected that the option to do that doesn't exist as the protocol specifically mentioned for that functionality and also, not being able to remove a token from the `rewardTokens` array could be dangerous in a lot of different cases, like a vulnerability, upgrade of the reward token, even a simple change of mind.
## Impact
Removing a reward token is not possible
## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/703fd3604069489937037f20490ec8c492c0508e/StakingV2/src/Lock.sol#L18
## Tool used

Manual Review

## Recommendation
Implement the functionality to remove a token.

**Comment by samuraii77** [comment]
Escalate

According to Sherlock rules:
>The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

>Example: The README states "Admin can only call XYZ function once" but the code allows the Admin to call XYZ function twice; this is a valid Medium

The protocol clearly mentioned the functionality to remove reward tokens multiple times in the contest README. As per the rules, the issue should be a valid medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> According to Sherlock rules:
> >The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.
> 
> >Example: The README states "Admin can only call XYZ function once" but the code allows the Admin to call XYZ function twice; this is a valid Medium
> 
> The protocol clearly mentioned the functionality to remove reward tokens multiple times in the contest README. As per the rules, the issue should be a valid medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by santipu03** [comment]
I forgot to add a comment to this issue but the reason for invalidation was the following: 

> The protocol team decided to delete the token removal functionality to prevent data corruption if a token were readded. For this reason, this is the intended design of the protocol.

I've commented the same in similar issues such as 14, 102, 203, and 211.

**Comment by samuraii77** [comment]
I agree that they might have decided to remove it but that decision was not mentioned anywhere and thus, issue should be valid.

**Comment by nevillehuang** [comment]
Agree with lead judge judgement. It is stated in the contest details that re-adding a remove token will corrupt the reward data. So it is valid to delete token removal functionality to permanently eliminate the following centralization risk from occuring.

> Re-adding a removed token will corrupt the reward data.

Planning to reject escalation and leave issue as it is

**Comment by samuraii77** [comment]
According to the rule I mentioned in my escalation comment and the fact that it wasn't mentioned anywhere that they will remove that functionality, issue should be a valid medium. What rule of Sherlock makes this an invalid issue, could you please quote it?

**Comment by nevillehuang** [comment]
Still planning to reject escalation based on comments [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/287#issuecomment-2143115734). Additionally, the same argument can also be applied where it is also not mentioned anywhere the protocol requires removal as a core contract functionality.

**Comment by samuraii77** [comment]
Hey, I will quote the Sherlock rules again as I think they are very clear as to what the severity for the issue should be:
>The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

The expected functionality regarding token removal is clear and it is in the README. The impact is definitely limited but rules are clear and according according to them, issue should be assigned medium severity. Also mentioning again that the protocol never mentioned about their intentions and their decisions to remove that functionality before or during the contest, thus it is not a valid argument to invalidate the issue because of that.

**Comment by nevillehuang** [comment]
@samuraii77 In addition to your original issue content at time of contest displaying no impact that matches sherlocks medium severity guidelines (DOS/fund loss), I believe my original judgement still applies.

**Comment by samuraii77** [comment]
@nevillehuang 

The rules are clear for this issue. Irrespective of whether the impact is low or unknown, the issue should still be a medium as clear by the Sherlock rule I quoted above.

For the last issue we discussed, you pinpointed an exact rule that invalidates my issue and I agree with it as the rules are clear and confirm your decision. However, the rules for this issue are clear as well and this time, they confirm my issue. I believe it would be unfair to invalidate one of my issues because of a clear Sherlock rule and then invalidate another one of my issues despite the rule clearly confirming the validity of the issue.

**Comment by nevillehuang** [comment]
I still stand by my previous [here](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/287#issuecomment-2150729611). There is no impact shown in the original submission as to why removal of token should be allowed, while eliminating the removal of tokens benefits the protocol my permanently removing the risk of corrupting rewards. Still planning to reject escalation and leave issue as it is.

**Comment by samuraii77** [comment]
The rule is very clear regarding the issue.

>The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. 

The README clearly mentioned of the existence of such functionality and never mentioned anything about removing it before or during the contest.

>Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity. High severity will be applied only if the issue falls into the High severity category in the judging guidelines.

That statement is clearly broken as the functionality does not exist. The impact is limited and I would definitely agree that it's low however the rule clearly states that even if the impact is low/unknown, the issue should still be assigned a Medium severity.

There is no point for debate here as the rules are clear. The only reason why this issue would be invalidated is just a personal opinion/preference not supported by any rule.

I will not comment on this issue anymore and will leave it to you to make the decision.

**Comment by WangSecurity** [comment]
The protocol indeed mentioned token removal functionality in the README, but I don't see any broken statement from the README. The README doesn't say that there should be a functionality for it, the QA says that this functionality would corrupt the reward data. Hence, there's no broken functionality that should hold according to README. Moreover, there is no impact from that vulnerability and in fact, it's helpful for the protocol to not implement this functionality.

Hence, the decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [samuraii77](https://github.com/sherlock-audit/2024-05-gamma-staking-judging/issues/287/#issuecomment-2140181945): rejected
