### ISSUE TITLE
maushish - `_earned` arithmetic calculations are wrong due to which it always show zero earnings.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-05-gamma-staking-judging#288]
maushish

high

# `_earned` arithmetic calculations are wrong due to which it always show zero earnings.

## Summary
The current implementation of `earned` is wrong it leads to a subtraction of  `rewardDebt` from `rewardDebt` due to which all earnings processing is wrong. 
## Vulnerability Detail
In the current implementation of  `_earned`, you will see:
>earnings = rewardInfo.cumulatedReward * balance.lockedWithMultiplier - rewardDebt[_user][_rewardToken];

```solidity
    /// @notice Calculates the earnings accumulated for a given user and reward token.
    /// @dev Calculates the net earnings by multiplying the accumulated reward with the user’s locked multiplier and subtracting the reward debt.
    /// @param _user The address of the user for whom to calculate earnings.
    /// @param _rewardToken The token address for which earnings are calculated.
    /// @return earnings The calculated amount of earnings for the user in terms of the specified reward token.
    function _earned(
        address _user,
        address _rewardToken
    ) internal view returns (uint256 earnings) {
        Reward memory rewardInfo = rewardData[_rewardToken]; // Retrieves reward data for the specified token.
        Balances memory balance = balances[_user]; // Retrieves balance information for the user.
        earnings = rewardInfo.cumulatedReward * balance.lockedWithMultiplier - rewardDebt[_user][_rewardToken]; // Calculates earnings by considering the accumulated reward and the reward debt.
    }
```
For `rewardDebt` we have `_updateRewardDeb` here,

```solidity
    /// @notice Updates the reward debt for all reward tokens based on the current cumulated rewards and the user's locked balances.
    /// @dev Iterates over all reward tokens and recalculates the reward debt for the specified user, based on their locked balances multiplied by the accumulated rewards for each token.
    /// @param _user The address of the user for whom the reward debt is being recalculated.
    function _updateRewardDebt(address _user) internal {
        Balances memory bal = balances[_user]; // Retrieve the current balance information for the user.

        for (uint i = 0; i < rewardTokens.length; ++i) {
            address rewardToken = rewardTokens[i]; // Access each reward token.
            Reward memory rewardInfo = rewardData[rewardToken]; // Get the current reward data for each token.

            // Recalculate the reward debt for the user based on their locked balances and the accumulated rewards for the token.
            rewardDebt[_user][rewardToken] = rewardInfo.cumulatedReward * bal.lockedWithMultiplier;
        }
    }
```
>[!IMPORTANT]
Now as you can see what `_earned` calculating is completely wrong
*earnings = rewardInfo.cumulatedReward * balance.lockedWithMultiplier - rewardDebt[_user][_rewardToken];
rewardDebt[_user][rewardToken] = rewardInfo.cumulatedReward * bal.lockedWithMultiplier;
earnings = rewardDebt[_user][_rewardToken] - rewardDebt[_user][_rewardToken];*

## Impact
`_earned` will always show **ZERO** earnings due to which:
- User won't be able to see how much rewards are claimable as `claimableRewards` uses `_earned`.
- During staking wrong `rewardUpdates` will be pushed as `_updateReward` uses `_earned`.
## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L455
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L213
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L614
## Tool used

Manual Review

## Recommendation
Define a function that calculates all the claimed rewards by the user then simply subtract the amt by the `rewardDebt`.

**Comment by maushish** [comment]
Yeah, the reason for such a huge mistake is that this finding was reported in a rush, my sincere apologies.
