### ISSUE TITLE
turvec - Users may be forced to leave out some of their rewards to be able to withdraw their funds without having to face extra lock time with no rewards

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#302]
turvec

medium

# Users may be forced to leave out some of their rewards to be able to withdraw their funds without having to face extra lock time with no rewards

## Summary
Users may be forced to leave out some of their rewards to be able to withdraw their funds without having to face extra lock time with no rewards

## Vulnerability Detail
It is intended that users are allowed to exit their lock with no penalty after the lock period has passed. However this is not so as users can only exit their lock without extra lock time if called **before** the lockperiod expires. However, the issue here is that if they evenly choose to do this in other to avoid that, they will be force to leave out some remaining rewards left to their lockPeriod, as they explained it in the docs

| In such a case, it is intended that the user will no longer receive rewards until the end of this unlock time.

 The example in the tests shows that if user does not exit before their expiryperiod, even if they exit exactly on thier lockPeriod, they will face an extra lock time with no rewards:
 ```solidity
 User B:
- lockPeriodByMultiplier = 60 days
- Staked = 60 days
- remainTime = 30 - (60) % 30 = 30 days left
```
Also if they decide to exit before their lock period, they will lose 1 day left of their rewards

```solidity
User C:
- lockPeriodByMultiplier = 60 days
- Staked = 59 days
- remainTime = 60 - (59) % 60 = 60 - 59 = 1 day left
```
## Impact
Users may be forced into to leave out some of their rewards or face extra lock time with no rewards, in both ways losses some rewards

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L600

## Tool used

Manual Review

## Recommendation
Consider allowing stakers to exit after reaching their lockPeriod by marking it as completed without auto relocking, to allow them withdraw anytime as long as they have passed the grace period and can choose to relock again

**Comment by turvec** [comment]
Escalate

This issue should be valid for the reasons:

- As we have already seen issues reported are all due to this `intended design` I have mentioned, every user trying to exit as late as possible in order to not miss out on new potential rewards, or miss out on their remaining reward due to the auto-relocking not after expired time but exactly at expired time.

- This point the core issue and the need for an at least 1 day grace period before auto-relocking or the recommendation above
