### ISSUE TITLE
0xreadyplayer1 - Users will receive rewards worth less in the event of  USDC depeg when staking same amount of tokens as others did who enjoyed more rewards

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-gamma-staking-judging#44]
0xreadyplayer1

medium

# Users will receive rewards worth less in the event of  USDC depeg when staking same amount of tokens as others did who enjoyed more rewards

## Summary
The protocol mentioned that they are willing to use usdc token as the reward token in their readme

```markdown
If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase

or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant?

Are there any types of weird tokens you want to integrate?

The tokens we expect to interact with would be standard ERC-20 tokens. 

The staking token will be a standard ERC-20 token. The reward tokens will also be standard ERC-20 tokens.

There is a whitelisting process for which reward tokens we would allow to be used as rewardTokens in function addReward, 

which is an admin function. This process would only allow reward tokens that comply with the ERC-20 standard to be distributed

to the stakers. We would also include USDC and USDT on the chains we mentioned in the previous question.

```

see the line `We would also include USDC and USDT on the chains we mentioned in the previous question.`

So the protocol intends to use `USDC` as a `Reward Token`

But the calculation of rewards calculation does not take into account the value of tokens 

being rewarded with respect to staked amount rather it just checks the amount .

This logic leads the contract to accrue less rewards for a user

when they claim their rewards in the depeg event of usdc ( as happened in the past )

when usdc is a reward token and will receive less rewards by claiming rewards after maturity of their lock ( e.g 30 days passed since lock ) when USD-worth of usdc tokens  is less ( 1 USDC=0.87$ ) than the people who claim those rewards

when there's no depeg event i.e  USDCs have more worth ( 1 USDC= 0.99 $ ) when even both users have staked exact same amount of staking tokens

This is not an external reliant issue as the protocol needs to be fair and correctly give equal rewards to users

who has staked same token balance of staking tokens otherwise there's not a fair distribution of rewards

leading to loss of significant rewards to some users.

## Vulnerability Detail
Anyone can approve their `stakingTokens` to the contract and lock their staking tokens for some time like 30 days 60 

days based on the type of staking they want to do .

let's say for simplicity , the type is 0 .

Now when the staker stakes their tokens this way 

```solidity
 lock.stake(100e18, user1, 0);
```
They are staking their 100 usdc tokens for 30 days ( suppose type 0 corresponds to 30 days lock and reward token is USDC )

Now inside stake , we see following code

```solidity
function stake(
        uint256 amount,
        address onBehalfOf,
        uint256 typeIndex
    ) external override {
        _stake(amount, onBehalfOf, typeIndex, false);
    }
```

where theres only one function call to internal `_stake`

```solidity
/// @notice Handles the internal logic for staking tokens, applying specified lock types and managing reward eligibility.
    /// @dev This function updates rewards, manages balances, and logs the staking process through events.
    ///      It ensures the amount and lock type are valid, adjusts token balances, and optionally handles token transfers for re-staking.
    /// @param amount The amount of tokens to be staked.
    /// @param onBehalfOf The address for which tokens are being staked.
    /// @param typeIndex The index of the lock type to apply, affecting reward multipliers and lock durations.
    /// @param isRelock Specifies whether the staking is for relocking already staked tokens.
    function _stake(
        uint256 amount,
        address onBehalfOf,
        uint256 typeIndex,
        bool isRelock
    ) internal whenNotPaused {
        if (typeIndex >= lockPeriod.length || amount == 0) revert InvalidAmount();

        _updateReward(onBehalfOf);
        
        Balances storage bal = balances[onBehalfOf];

        bal.locked += amount;
        lockedSupply += amount;

        uint256 multiplier = rewardMultipliers[typeIndex];
        bal.lockedWithMultiplier += amount * multiplier;
        lockedSupplyWithMultiplier += amount * multiplier;
        _updateRewardDebt(onBehalfOf);


        locklist.addToList(
            onBehalfOf, 
            LockedBalance({
                lockId: 0, // This will be set inside the addToList function
                amount: amount,
                unlockTime: 0, 
                multiplier: multiplier,
                lockTime: block.timestamp,
                lockPeriod: lockPeriod[typeIndex],
                exitedLate: false
            })
        );

        if (!isRelock) {
            IERC20(stakingToken).safeTransferFrom(
                msg.sender,
                address(this),
                amount
            );
        }

        emit Locked(
            onBehalfOf,
            amount,
            balances[onBehalfOf].locked
        );
    }
```
The amount is recorded .

```solidity
  Balances storage bal = balances[onBehalfOf];

        bal.locked += amount;
        lockedSupply += amount;

        uint256 multiplier = rewardMultipliers[typeIndex];
        bal.lockedWithMultiplier += amount * multiplier;
        lockedSupplyWithMultiplier += amount * multiplier;
        _updateRewardDebt(onBehalfOf);


        locklist.addToList(
            onBehalfOf, 
            LockedBalance({
                lockId: 0, // This will be set inside the addToList function
                amount: amount,
                unlockTime: 0, 
                multiplier: multiplier,
                lockTime: block.timestamp,
                lockPeriod: lockPeriod[typeIndex],
                exitedLate: false
            })
        );
```
however there are two function calls that we might think will determine the real value of the tokens and allocate rewards accordingly i.e we believe rewards will be based on the USD value of the staking token to  correctly calculates the amount of reward tokens ( USDC ) to give to users so that people staking same USD worth tokens will get same rewards so that none of them loses their rewards 

```solidity
  _updateReward(onBehalfOf);
  ..//snip
  _updateRewardDebt(onBehalfOf);

```

Let's look at each 

```solidity
 /// @notice Updates the accumulated rewards and reward debts for all tokens for a specific user account.
    /// @dev Iterates over all reward tokens, updates each token's accrued rewards for the given account, and adjusts the reward debt accordingly.
    /// @param account The address of the user for whom rewards are being updated.
    function _updateReward(address account) internal {
        uint256 length = rewardTokens.length; // Determine the number of reward tokens.
        Balances storage bal = balances[account]; // Access the balance record for the user.

        for (uint256 i = 0; i < length; ) {
            address token = rewardTokens[i]; // Access each token.
            Reward memory rewardInfo = rewardData[token]; // Get the reward data for the token.

            rewards[account][token] += _earned(account, token); // Update the rewards for the user based on what has been earned so far.
            rewardDebt[account][token] = rewardInfo.cumulatedReward * bal.lockedWithMultiplier; // Update the reward debt based on the latest reward information.

            unchecked {
                i++;
            }
        }
    }
    
    // and `_earned` method is follows
    
     /// @notice Calculates the earnings accumulated for a given user and reward token.
    /// @dev Calculates the net earnings by multiplying the accumulated reward with the user’s locked multiplier and subtracting the reward debt.
    /// @param _user The address of the user for whom to calculate earnings.
    /// @param _rewardToken The token address for which earnings are calculated.
    /// @return earnings The calculated amount of earnings for the user in terms of the specified reward token.
    function _earned(
        address _user,
        address _rewardToken
    ) internal view returns (uint256 earnings) {
        Reward memory rewardInfo = rewardData[_rewardToken]; // Retrieves reward data for the specified token.
        Balances memory balance = balances[_user]; // Retrieves balance information for the user.
        earnings = rewardInfo.cumulatedReward * balance.lockedWithMultiplier - rewardDebt[_user][_rewardToken]; // Calculates earnings by considering the accumulated reward and the reward debt.
    }
```
Okey this just updated the earned rewards before stake

how about this method 

```solidity
  /// @notice Updates the reward debt for all reward tokens based on the current cumulated rewards and the user's locked balances.
    /// @dev Iterates over all reward tokens and recalculates the reward debt for the specified user, based on their locked balances multiplied by the accumulated rewards for each token.
    /// @param _user The address of the user for whom the reward debt is being recalculated.
    function _updateRewardDebt(address _user) internal {
        Balances memory bal = balances[_user]; // Retrieve the current balance information for the user.

        for (uint i = 0; i < rewardTokens.length; ++i) {
            address rewardToken = rewardTokens[i]; // Access each reward token.
            Reward memory rewardInfo = rewardData[rewardToken]; // Get the current reward data for each token.

            // Recalculate the reward debt for the user based on their locked balances and the accumulated rewards for the token.
            rewardDebt[_user][rewardToken] = rewardInfo.cumulatedReward * bal.lockedWithMultiplier;
        }
    }
```

clearly this method is also updating the debt based on the `amount` of tokens and not their value.

These functions do not check the value of tokens being deposited , rather just the number - amount of tokens being deposited.

So in the event when let's say there are two users

Alice and Bob both deposit 100 million staking tokens 30 days ago & now its time to get the rewards.

- Alice deposits 100 million Staking tokens with  `1 staking token = 4$` and stake them for some rewards multiplier config that calculates the amount of rewards to give is `250k rewards` token i.e  `250k usdc` when 1 USDC=1$

So essentially , the system has given the rewards based on following rate

100*10^6 * 4 = 400 Million USD deposited 
250k USDC =250k  *1$ = 250k $ rewarded

which means the rate was `deposited/4 $`

`Alice got 250k$ `worth of tokens for 100 million staking tokens deposit

A depeg event occurs the next day and Bob does not notice the depeg event of USDC dropping from `1$` to `0.87$`

Now it's time for bob to get his rewards and his rewards are calculated similarly

deeming him to get 250k USDC

but the value of those 250k USDC  = 250k*0.87$ = 217500 ~ `217k$`

`Bob Got 217k$` worth of USDC rewards for staking the same amount of staking tokens as alice did

but `Bob incurred a Loss of `33k$` which is huge.

### Latest USDC depeg reference
Recent `depeg event` in `March 2023`, where USDC price went as low as `87 cents` [Check here ](https://decrypt.co/123211/usdc-stablecoin-depegs-90-cents-circle-exposure-silicon-valley-bank).

### Similar Confirmed High severity finding Reference
https://github.com/code-423n4/2024-03-ondo-finance-findings/issues/278

## Impact
The protocol will allow getting very less rewards to users in depeg event when they have staked 

the same amount of staking tokens as others did but will incur a huge loss in terms of value.

This error is based on the fact that rewards are calculated in terms of amount of staked tokens

and multipliers config and not  determined according to the underlying value of the staked assets

### Severity
As this issue `Causes a loss of funds but requires certain external conditions or specific states` , according to sherlock rules , it's at least a medium severity issue.

The judge can decide whether to upgrade it or not.

## Code Snippet
https://github.com/sherlock-audit/2024-05-gamma-staking/blob/main/StakingV2/src/Lock.sol#L245

## Tool used
Manual Review
## Recommendation
Determine the value of tokens being staked and then determine the amount of tokens to provide in rewards based on that value.

This might require some additional work but this will make the system more robust and market ready and secure and reliable for users.

**Comment by santipu03** [comment]
There's no vulnerability here, the `Lock` contract is clearly designed to distribute tokens between its stakers based on the amounts, not the value. Most of the staking contracts on Defi, including this one, don't implement oracles because they don't care about the token prices, they distribute only based on the token amounts, for example, the famous [Masterchef](https://github.com/sushiswap/sushiswap/blob/271458b558afa6fdfd3e46b8eef5ee6618b60f9d/contracts/MasterChef.sol) staking contract.

**Comment by 0xreadyplayer1** [comment]
You are correct but here's in the event of USDC Depeg , the reported issue clearly
```
Causes a loss of funds but requires certain external conditions or specific states(like USDC Depeg), or a loss is highly constrained.

The losses must exceed small, finite amount of funds, and any amount relevant based on the precision 
 
or significance of the loss.
```

i believe for that reason , the issue MUST be valid.

However i leave it to the head of judging .
